name: OWASP ZAP Cron Job
on:
  schedule:
    - cron: '*/10 * * * *'
jobs:
  dast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v2
      - name: Executar OWASP ZAP
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: https://voluntariamos.netlify.app/
          zap-target-params: "-config globalexcludeurl.url_list.url.regex=.*logout.*"
